# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'itnetX Belgium'
tagline:             'Technical Blog'
description:         'In-depth technical content provided by the itnetX team'
url:                 'http://www.itnetx.be'
baseurl:             'https://itnetxbe.github.io/blog'
paginate:            5

# About/contact
author:
  name:              itnetXBE
  url:               https://twitter.com/itnetX_BE
  email:             info@itnetx.be

# Custom vars
version:             1.0.0
