# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Hernando Salas
tagline:             'Data Scientist and Software Engineer.'
description:         'The internet home of Hernando Salas. Data Scientist. Software Engineer.'
url:                 'http://hernandosalas.github.io'
baseurl:             'https://hernandosalas.github.io'
blogurl:             '/blog'
paginate:            5

# Pagination
paginate_path:       'blog/page:num/'

# About/contact
author:
  name:              Hernando Salas
  url:               https://hernandosalas.github.io
  email:             hernandosalas@gmail.com

# Custom vars
version:             1.0.0

#Gems
gems:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-seo-tag

# Compress.html
compress_html:
  comments: ["<!-- ", " -->"]


# jekyll-assets
assets:
  compress:
    js: true
    css: true

  assets:
    - "*.png"
    - "*.jpeg"
    - "*.jpg"

  sources:
    - public/project-images/card-headers