# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'itnetX Belgium'
tagline:             'Technical Blog'
description:         'In-depth technical content provided by the itnetX team'
url:                 'http://hernandosalas.github.io'
baseurl:             'https://hernandosalas.github.io'
paginate:            5

# About/contact
author:
  name:              itnetXBE
  url:               https://hernandosalas.github.io
  email:             info@itnetx.be

# Custom vars
version:             1.0.0
